language: python
dist: trusty
sudo: required
services:
- docker
python:
- '3.6'
env:
  global:
  - secure: BjN9fOnOc+P89XAVPQpp4sedQsqPCz0IRlqohcBvM+azf5XOWcZXIEQwKolNjO888/kylO/W6HQF0uzjZqjcNDX5fBS56rOX685ELlGba3I8022xDG2IIJr7Ihc8EtILgDXiQacdTIOwlZhiPGbEl1uueCY+CWhhx8y0t6FwUnfSi8xqymMY/mbVdEq2/xXhbL+wq0OvXPJUahUiLEeY89FQDMIysJPydw2G/TMsFPm2GbYF+YX+MDD3Wm1Jk6UoH68bgWX2zD9S/H9zZuaGJg91N4knrP1WuoekF9j1naESx5q5VBmJlSJ9RTPoCaiaEWpS482CFe2CyimCGdxmTzMXjQ1bWGgNyZ9c4ieBYAIBHYJH2VkBsQZzMNp3v2lJV47fLFlcXtSgKg8Obm5Z0NV9gNJ4Ky11nUkEcZzPKhhkflK+bxuovHEwe7Kpht+MKedlSZk4os2SQeJyzBR/t+V0SPciBqeZA13yANBfqCxnCM3UetKhMPSbM7pDGpsMlM21ThFCRpv3hwHG8d4z7e9vXPJKtj/Ai5N1SVdgCNMox/u4N00fFZrlTUbeDEDgC6wLjXORLh8rQey9U7xpfa91iZzxoLma1zDofdunB0rwVtJkyxt4QhEEAVv2KF//wnpxceHkLHPAvNlWDyh2ngFiwPzhO3F5tVdLjSUoqVY=
  - secure: OYby5o4k2bQrH0EKrSUNynZoi2RpCXw632cATRb/adJkL2PzSKQ9HOQRLYj8Gx7OgpvuFvwh9ujqceRVIdwEn/sjh8PEnJaC+wu5TL32DVrvB+EH9IOYLTHX8nvWeMYaeUEccMsW1pGT+WKfuR3mEBkvhQOOis/H+gvmiR+G+PmIFdz1xAoX6KapsTpMXg1bnISVMeD6BZ4Wi7TsRH/DFw9Clx5tsZaUI+RJwPOXLj6BhRa9QzNqvKJ3KPSsL3keC06EBNgsXAEHWVjTk6ouOoXkO3ENgvqjqxCjqkTh//D8iMi0KhZQEB7RU0T0Iyf3AL6GornpUOYO97dnNNH0aU4FDE27tdFu1oAveRz0+EZ20YfVfnenj8uWWTeC1jjZVyJJ++b8IqDb1YVodjtxYLR86RwiUjsaLMWSB/KFZms8YW1FsYvcaL8HQpJNi1QkB3a/+db3JyrtjmLedUKOkJetsxfbS3WLnvYWCnM8NaHYdMgt0i6QPQ4Hu2Ja8Krjq+9EJ6RwQM+ZD9pdlRbGcfyvDIfvmraPceQ7anN9JDgJiq4neuK2CxNlypV4F6tCbDuOqB/FXLoh1JNa/FjHVIlsmNKMt0v6f9DMj8ZXYB739jNwYyELSdIn27mJOn9S+k/Bjk6T8K88SDy4s3zRNpr98k4yJs4MmivVqNx/6Wk=
  - FLASK_ENV=development
  - secure: F1Jv1QztEwEw89gcmKZvEM4AKc/T+U76aicNC/eQCdZgyDI5XntFrdpJ0oMnYPa+WX+OdO6TS55zut314qVJCLKzAfR8MpLz+YE8r6TwB4oizZwqrraMfpN/FbcNXJQmCgou9rHIY87Q0093HGtoYgc1/xev2goJZDEaa40wkIHZhjsw7hikUHBFGYyDOn7B/pLLJ+N5hfXk79iTM7fDtINdIC4b5CTaSo2hETxV9QW3T3MNw3vFWZtRhjOaIYbXznBrbZtxEwTDV90Fje+mYGHOppGMAgsgQNMjp4IBOwQMJpZNf0ECBR7apFTuCTlA5WpLPnaNba6x3r5VoDlDB0lUkpIzqWVMFXm962iTAKHa4+dfmEZp4lLZzuNtkhdB8x8OQY3FeAWVUFxXQn0FIj92kW/mcflKuJLmzZiMb/AzylpLHaB5MdtkcVGMSqzN8B192t+JUuZom8AedQ60bqcvYZmyIBJL348YL+LkGwKaZE7zIXDDHK2VXXUUGt1lgNwV6FL8bywpXU4rTws0qPQ192NhEuMrl0i7RD23ALruA0s8YM+HzOqE9bxrOQvjiIwZUymqm7GzBdonULJEr4U5EAbHbTPNDQsGE/k2GCYL+SDKtAc7XPQFn6kn02m8+ETLagG4hAIqET7aBaPvRjykZU2ETF4gma4xEI1wR0I=
install:
- pip install pipenv
- pipenv install --dev
before_script:
- export MODE=CI
script:
- flake8
deploy:
- provider: script
  script: bash deploy/travis.sh
  on:
    tags: true
notifications:
  slack:
    rooms:
    - secure: xsGLjigcoVbbQljrB91BZ5VnXchIr0oxEgvW5QiKnHUqMNLZYctD5Dl3eLis3U1nThPmspt0CbSuCag9QuFK+f36h8yBJtCAEVJvEYpt+BRTwWYiw9fBT8SgLmilVInwF1SH5u6Zr+KTRDR3QXOG7ZwpFUa6zZ3yYNbKGXyFGD0vLMnwgBqIdCEYmA4ryurvg6yngr6iTv9OctRqeGDWprlhyIrmP4lnn0SnGuks9zxW39AzX1234JM05ys4UwbMno0j5zlY+uECSYJkW/WV4UtSdJQeF6+2qcguveNswh1w+Otlts471hWRbPZfFHbCHJlnTM7x2HeG1IuLe8yhZHiwclxPtYPln5p4kTtgCON9gXNKpDSeXoAYJbPF2K5k9B/732GlKhilEqEnD06z281PezAZ8HmPaprFA4/fVFQQ9Yqvwk4SKNEh1SUfTBfYSMY0XZoXz/sZ898hJAV4GQ5ImEog1cZnFdD9kqJl1zIu+FSTtDY5PqfSUn+iFeEJbo6gBsPyKrdgNaN/1hvLnthudiSW+E1DNIF1nxZ/lA4dQdOp0tSCR3nj5XZMKgJgAyZAUD2mXGPZAJUamSnxHRzPFurD+54mqMcWFxLp3Y0lNuBdez5l9SjdH+ZagYpvdTZ1aeAEmVpvCgSrcb8voKmH4J2bFTHEQ1rdUQyD+tE=
    on_success: always
    on_failure: always
