language: python
dist: trusty
sudo: required
services:
- docker
python:
- '3.6'
env:
  global:
  - FLASK_ENV=development
  - secure: ZCEZlbNsERyKWBudUbAjOIOjr7JxI86GKheaAt/f8TrvbukFqoa4n4ngD+XA7jCM3okAM2uVBjeBAmFqMYbfgotvwaJoy8HDS80jaPif0yjG2ZhxqP+UVRWPcs04fM5c+y4nnwrhGc/t0NExtCs7jwK+zJg7ulV7yNfIKc1lz1BEbVmq5lamxTHuMfI7rY+yr+0lcQY1eikvgj6XDRULRtFj0t9yqHYqIm6L74gUFfarokpQHm6Tv6y7iYY6t3kIJsNKZ5HQZIh+BORUj/9Sd6ZrfxKm26J5AxRY6jNeOoVZmn8sVyqKl0eRg9MzAR5FSYkpXY6ZZK08ci/SQZ1pdOOEL3n0HZ+HbIi0xbjtfQHHUaUwGIffgCZhxFs0Xkjc4R4XpfG0YXRt9BdIMjuGeYuK30Qy7QPJsr9oKwKQIym95fkGVWq9Kj+RlhzkTgz0SQHxtAdmOyYUNIdexd0S0KSTiaKbfwHuv+hzfCEk5qMVCeGWA52hiefGs712I2n4D1Dz8h0DP4peqJxxmYXqmdUAQpnklq+j/eXhzkyP9/xsnu+kVjgy8LfrHeH5/LmqreagxunmJErwR2bJTWDWpvv7g+J5LD4CKk/imzHr+rlldoyJVjgC+NHdBFdldyO0u+EX6HT2/PMutFgFJBl7ZjSG9lFaXkDNt4dW1tzlEOc=
install:
- pip install pipenv
- pipenv install --dev
before_script:
- export MODE=CI
script:
- flake8
deploy:
- provider: script
  script: bash deploy/travis.sh
  on:
    tags: true
notifications:
  slack:
    rooms:
    - secure: xsGLjigcoVbbQljrB91BZ5VnXchIr0oxEgvW5QiKnHUqMNLZYctD5Dl3eLis3U1nThPmspt0CbSuCag9QuFK+f36h8yBJtCAEVJvEYpt+BRTwWYiw9fBT8SgLmilVInwF1SH5u6Zr+KTRDR3QXOG7ZwpFUa6zZ3yYNbKGXyFGD0vLMnwgBqIdCEYmA4ryurvg6yngr6iTv9OctRqeGDWprlhyIrmP4lnn0SnGuks9zxW39AzX1234JM05ys4UwbMno0j5zlY+uECSYJkW/WV4UtSdJQeF6+2qcguveNswh1w+Otlts471hWRbPZfFHbCHJlnTM7x2HeG1IuLe8yhZHiwclxPtYPln5p4kTtgCON9gXNKpDSeXoAYJbPF2K5k9B/732GlKhilEqEnD06z281PezAZ8HmPaprFA4/fVFQQ9Yqvwk4SKNEh1SUfTBfYSMY0XZoXz/sZ898hJAV4GQ5ImEog1cZnFdD9kqJl1zIu+FSTtDY5PqfSUn+iFeEJbo6gBsPyKrdgNaN/1hvLnthudiSW+E1DNIF1nxZ/lA4dQdOp0tSCR3nj5XZMKgJgAyZAUD2mXGPZAJUamSnxHRzPFurD+54mqMcWFxLp3Y0lNuBdez5l9SjdH+ZagYpvdTZ1aeAEmVpvCgSrcb8voKmH4J2bFTHEQ1rdUQyD+tE=
    on_success: always
    on_failure: always
