language: python
dist: trusty
sudo: required
services:
- docker
python:
- '3.6'
env:
  global:
  - FLASK_ENV=development
  - secure: ZCEZlbNsERyKWBudUbAjOIOjr7JxI86GKheaAt/f8TrvbukFqoa4n4ngD+XA7jCM3okAM2uVBjeBAmFqMYbfgotvwaJoy8HDS80jaPif0yjG2ZhxqP+UVRWPcs04fM5c+y4nnwrhGc/t0NExtCs7jwK+zJg7ulV7yNfIKc1lz1BEbVmq5lamxTHuMfI7rY+yr+0lcQY1eikvgj6XDRULRtFj0t9yqHYqIm6L74gUFfarokpQHm6Tv6y7iYY6t3kIJsNKZ5HQZIh+BORUj/9Sd6ZrfxKm26J5AxRY6jNeOoVZmn8sVyqKl0eRg9MzAR5FSYkpXY6ZZK08ci/SQZ1pdOOEL3n0HZ+HbIi0xbjtfQHHUaUwGIffgCZhxFs0Xkjc4R4XpfG0YXRt9BdIMjuGeYuK30Qy7QPJsr9oKwKQIym95fkGVWq9Kj+RlhzkTgz0SQHxtAdmOyYUNIdexd0S0KSTiaKbfwHuv+hzfCEk5qMVCeGWA52hiefGs712I2n4D1Dz8h0DP4peqJxxmYXqmdUAQpnklq+j/eXhzkyP9/xsnu+kVjgy8LfrHeH5/LmqreagxunmJErwR2bJTWDWpvv7g+J5LD4CKk/imzHr+rlldoyJVjgC+NHdBFdldyO0u+EX6HT2/PMutFgFJBl7ZjSG9lFaXkDNt4dW1tzlEOc=
install:
- pip install pipenv
- pipenv install --dev
before_script:
- export MODE=CI
script:
- flake8
deploy:
- provider: script
  script: bash deploy/travis.sh
  on:
    tags: true
notifications:
  slack:
    on_success: always
    on_failure: always
    secure: H6skowOKVl821xiJNXmV+eUYPty+EiCFBHC8dbr+QXXxYnzsUV/rgZZXqOVY+ZIl805sy0uC6+chVluPm472XnbGk6yV5zo6BRQmzLeMKjkUdwfIONjOXfqQclLuLHyea5ukHFzjFINpAZXbsyE/VuW/H++l05NoS9+uT4Fc7kWPQXhyFRD4UWPfCRowLyUVGsIagE4lmHhqbu5z6RyHqLHa2VcXHFVqJckH5PsUkBz2mwvrshvhBSXBh+x1gAgCMILG57sUE3HmsuLZkFf/LsVusWSlU92l/3iZVXOOeS9ezSTcg46FjvHzCQ7Kbm6Qe874CHMkGiuccqNrX7rf6EME1VRM5yF7iM+ncyIzno6filtjKt1H9q7mgK4iu9x8dqHXhwfkZHKSQLz/MxC1dhDGAN8cGcdG7Hw705PcPSXINwju8/mnGDqhFXvjal6CKdMnRzObSylOVxlqHY9t9laR9NuMorfiAMPR4hksKdhV1yPovbSWOtwo2DsZIHF26JExWibNWtrFHCS/C02KKR9ugqTK0UJOnsDqbrzClHCi8bm01NgK0KnbMqm7MozTa6RyjB06RDcwIpIyZ+xifmVxS/nUjliATonIDqr83fjUbMFz2Pk/gn5G0UuJbfxytHP7D2FZ/TGxprmAkLiiUmc2nuKk6AYD1+O5UQOkn0o=